default: &default
  adapter: postgresql
  pool: 5
  encoding: unicode
  timeout: 5000


development:
  <<: *default
  database: backyard-lion-international_development


test: &test
  <<: *default
  database: backyard-lion-international_test


production:
  <<: *default
  database: backyard-lion-international_production

cucumber:
  <<: *test
